//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the obstacleDetection package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __obstacleDetection__VE_HYPER_PARAMETERCONFIG_H__
#define __obstacleDetection__VE_HYPER_PARAMETERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace obstacleDetection
{
  class ve_hyper_parameterConfigStatics;

  class ve_hyper_parameterConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(ve_hyper_parameterConfig &config, const ve_hyper_parameterConfig &max, const ve_hyper_parameterConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ve_hyper_parameterConfig &config1, const ve_hyper_parameterConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ve_hyper_parameterConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ve_hyper_parameterConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ve_hyper_parameterConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ve_hyper_parameterConfig &config) const = 0;
      virtual void getValue(const ve_hyper_parameterConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ve_hyper_parameterConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ve_hyper_parameterConfig::* field;

      virtual void clamp(ve_hyper_parameterConfig &config, const ve_hyper_parameterConfig &max, const ve_hyper_parameterConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ve_hyper_parameterConfig &config1, const ve_hyper_parameterConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ve_hyper_parameterConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ve_hyper_parameterConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ve_hyper_parameterConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ve_hyper_parameterConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ve_hyper_parameterConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ve_hyper_parameterConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ve_hyper_parameterConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ve_hyper_parameterConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ve_hyper_parameterConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("minPoints"==(*_i)->name){minPoints = boost::any_cast<int>(val);}
        if("epsilon"==(*_i)->name){epsilon = boost::any_cast<double>(val);}
        if("minClusterSize"==(*_i)->name){minClusterSize = boost::any_cast<int>(val);}
        if("maxClusterSize"==(*_i)->name){maxClusterSize = boost::any_cast<int>(val);}
        if("xMinROI"==(*_i)->name){xMinROI = boost::any_cast<double>(val);}
        if("xMaxROI"==(*_i)->name){xMaxROI = boost::any_cast<double>(val);}
        if("yMinROI"==(*_i)->name){yMinROI = boost::any_cast<double>(val);}
        if("yMaxROI"==(*_i)->name){yMaxROI = boost::any_cast<double>(val);}
        if("zMinROI"==(*_i)->name){zMinROI = boost::any_cast<double>(val);}
        if("zMaxROI"==(*_i)->name){zMaxROI = boost::any_cast<double>(val);}
        if("xMinBoundingBox"==(*_i)->name){xMinBoundingBox = boost::any_cast<double>(val);}
        if("xMaxBoundingBox"==(*_i)->name){xMaxBoundingBox = boost::any_cast<double>(val);}
        if("yMinBoundingBox"==(*_i)->name){yMinBoundingBox = boost::any_cast<double>(val);}
        if("yMaxBoundingBox"==(*_i)->name){yMaxBoundingBox = boost::any_cast<double>(val);}
        if("zMinBoundingBox"==(*_i)->name){zMinBoundingBox = boost::any_cast<double>(val);}
        if("zMaxBoundingBox"==(*_i)->name){zMaxBoundingBox = boost::any_cast<double>(val);}
      }
    }

    int minPoints;
double epsilon;
int minClusterSize;
int maxClusterSize;
double xMinROI;
double xMaxROI;
double yMinROI;
double yMaxROI;
double zMinROI;
double zMaxROI;
double xMinBoundingBox;
double xMaxBoundingBox;
double yMinBoundingBox;
double yMaxBoundingBox;
double zMinBoundingBox;
double zMaxBoundingBox;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minPoints;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double epsilon;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minClusterSize;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int maxClusterSize;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double xMinROI;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double xMaxROI;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yMinROI;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yMaxROI;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double zMinROI;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double zMaxROI;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double xMinBoundingBox;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double xMaxBoundingBox;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yMinBoundingBox;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yMaxBoundingBox;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double zMinBoundingBox;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double zMaxBoundingBox;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ve_hyper_parameterConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ve_hyper_parameterConfig &__max__ = __getMax__();
      const ve_hyper_parameterConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ve_hyper_parameterConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ve_hyper_parameterConfig &__getDefault__();
    static const ve_hyper_parameterConfig &__getMax__();
    static const ve_hyper_parameterConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ve_hyper_parameterConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ve_hyper_parameterConfig::ParamDescription<std::string>::clamp(ve_hyper_parameterConfig &config, const ve_hyper_parameterConfig &max, const ve_hyper_parameterConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ve_hyper_parameterConfigStatics
  {
    friend class ve_hyper_parameterConfig;

    ve_hyper_parameterConfigStatics()
    {
ve_hyper_parameterConfig::GroupDescription<ve_hyper_parameterConfig::DEFAULT, ve_hyper_parameterConfig> Default("Default", "", 0, 0, true, &ve_hyper_parameterConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minPoints = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minPoints = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minPoints = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<int>("minPoints", "int", 0, "minPoints", "", &ve_hyper_parameterConfig::minPoints)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<int>("minPoints", "int", 0, "minPoints", "", &ve_hyper_parameterConfig::minPoints)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.epsilon = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.epsilon = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.epsilon = 0.7;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("epsilon", "double", 0, "epsilon", "", &ve_hyper_parameterConfig::epsilon)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("epsilon", "double", 0, "epsilon", "", &ve_hyper_parameterConfig::epsilon)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minClusterSize = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minClusterSize = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minClusterSize = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<int>("minClusterSize", "int", 0, "minClusterSize", "", &ve_hyper_parameterConfig::minClusterSize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<int>("minClusterSize", "int", 0, "minClusterSize", "", &ve_hyper_parameterConfig::minClusterSize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.maxClusterSize = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.maxClusterSize = 1000;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.maxClusterSize = 50;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<int>("maxClusterSize", "int", 0, "maxClusterSize", "", &ve_hyper_parameterConfig::maxClusterSize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<int>("maxClusterSize", "int", 0, "maxClusterSize", "", &ve_hyper_parameterConfig::maxClusterSize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.xMinROI = -30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.xMinROI = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.xMinROI = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMinROI", "double", 0, "xMinROI", "", &ve_hyper_parameterConfig::xMinROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMinROI", "double", 0, "xMinROI", "", &ve_hyper_parameterConfig::xMinROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.xMaxROI = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.xMaxROI = 30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.xMaxROI = 3.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMaxROI", "double", 0, "xMaxROI", "", &ve_hyper_parameterConfig::xMaxROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMaxROI", "double", 0, "xMaxROI", "", &ve_hyper_parameterConfig::xMaxROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yMinROI = -30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yMinROI = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yMinROI = -1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMinROI", "double", 0, "yMinROI", "", &ve_hyper_parameterConfig::yMinROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMinROI", "double", 0, "yMinROI", "", &ve_hyper_parameterConfig::yMinROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yMaxROI = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yMaxROI = 30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yMaxROI = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMaxROI", "double", 0, "yMaxROI", "", &ve_hyper_parameterConfig::yMaxROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMaxROI", "double", 0, "yMaxROI", "", &ve_hyper_parameterConfig::yMaxROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zMinROI = -2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zMinROI = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zMinROI = -1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMinROI", "double", 0, "zMinROI", "", &ve_hyper_parameterConfig::zMinROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMinROI", "double", 0, "zMinROI", "", &ve_hyper_parameterConfig::zMinROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zMaxROI = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zMaxROI = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zMaxROI = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMaxROI", "double", 0, "zMaxROI", "", &ve_hyper_parameterConfig::zMaxROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMaxROI", "double", 0, "zMaxROI", "", &ve_hyper_parameterConfig::zMaxROI)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.xMinBoundingBox = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.xMinBoundingBox = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.xMinBoundingBox = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMinBoundingBox", "double", 0, "xMinBoundingBox", "", &ve_hyper_parameterConfig::xMinBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMinBoundingBox", "double", 0, "xMinBoundingBox", "", &ve_hyper_parameterConfig::xMinBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.xMaxBoundingBox = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.xMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.xMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMaxBoundingBox", "double", 0, "xMaxBoundingBox", "", &ve_hyper_parameterConfig::xMaxBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("xMaxBoundingBox", "double", 0, "xMaxBoundingBox", "", &ve_hyper_parameterConfig::xMaxBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yMinBoundingBox = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yMinBoundingBox = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yMinBoundingBox = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMinBoundingBox", "double", 0, "yMinBoundingBox", "", &ve_hyper_parameterConfig::yMinBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMinBoundingBox", "double", 0, "yMinBoundingBox", "", &ve_hyper_parameterConfig::yMinBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yMaxBoundingBox = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMaxBoundingBox", "double", 0, "yMaxBoundingBox", "", &ve_hyper_parameterConfig::yMaxBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("yMaxBoundingBox", "double", 0, "yMaxBoundingBox", "", &ve_hyper_parameterConfig::yMaxBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zMinBoundingBox = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zMinBoundingBox = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zMinBoundingBox = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMinBoundingBox", "double", 0, "zMinBoundingBox", "", &ve_hyper_parameterConfig::zMinBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMinBoundingBox", "double", 0, "zMinBoundingBox", "", &ve_hyper_parameterConfig::zMinBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zMaxBoundingBox = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zMaxBoundingBox = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMaxBoundingBox", "double", 0, "zMaxBoundingBox", "", &ve_hyper_parameterConfig::zMaxBoundingBox)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr(new ve_hyper_parameterConfig::ParamDescription<double>("zMaxBoundingBox", "double", 0, "zMaxBoundingBox", "", &ve_hyper_parameterConfig::zMaxBoundingBox)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ve_hyper_parameterConfig::AbstractGroupDescriptionConstPtr(new ve_hyper_parameterConfig::GroupDescription<ve_hyper_parameterConfig::DEFAULT, ve_hyper_parameterConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ve_hyper_parameterConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ve_hyper_parameterConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ve_hyper_parameterConfig __max__;
    ve_hyper_parameterConfig __min__;
    ve_hyper_parameterConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ve_hyper_parameterConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ve_hyper_parameterConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ve_hyper_parameterConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ve_hyper_parameterConfig &ve_hyper_parameterConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ve_hyper_parameterConfig &ve_hyper_parameterConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ve_hyper_parameterConfig &ve_hyper_parameterConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ve_hyper_parameterConfig::AbstractParamDescriptionConstPtr> &ve_hyper_parameterConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ve_hyper_parameterConfig::AbstractGroupDescriptionConstPtr> &ve_hyper_parameterConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ve_hyper_parameterConfigStatics *ve_hyper_parameterConfig::__get_statics__()
  {
    const static ve_hyper_parameterConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ve_hyper_parameterConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __VE_HYPER_PARAMETERRECONFIGURATOR_H__
